environment:
    global:
      PYTHON: "C:\\Python36"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - pip --version
  - pip install -U virtualenv
  - pip --version
