environment:
    global:
      PYTHON: "C:\\Python27"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - python -m pip install pip==9.0.1
  # - python -m pip install -e git+git://github.com/atugushev/pip-tools@fix-issue-625#egg=pip-tools
  - python -m pip install pip-tools
  - python -V
  - pip-compile --version
  - cat setup.py
  - pip-compile
