environment:
    global:
      PYTHON: "C:\\Python36"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - C:\Python36\Scripts\pip --version
  - python -m pip install -e git+git://github.com/atugushev/pip@fix-issue-6841#egg=pip
  - pip install --upgrade pip
  - pip3 install --upgrade pip
  - pip3.6 install --upgrade pip
