environment:
    global:
      PYTHON: "C:\\Python36"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - python -m pip install -U pip
  - where python
  - pip --version
  - pip install setuptools
