environment:
    global:
      PYTHON: "C:\\Python36"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - python -m pip install --upgrade git+git://github.com/pypa/pip@master#egg=pip==19.3.dev0

build: false

test_script:
  - pip install pip
