environment:
    global:
      PYTHON: "C:\\Python36"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - echo STEP 1: Upgrade to the latest pip using module invocation
  - python -m pip install --upgrade git+git://github.com/atugushev/pip@fix-issue-6841#egg=pip

  - echo STEP 2: Upgrade pip using pip.exe
  - pip install --upgrade pip
